version: "3.9"
services:
  database:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=geodatabase
      - POSTGRES_USER=pgis
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
